;;; -*- lexical-binding: t; -*-

(add-to-list 'load-path "~/.emacs.d/mod/packaging")
(load "_repositories.el")
(load "_ensure.el")
(load "_use-package.el")
(load "_path.el")

(add-to-list 'load-path "~/.emacs.d/mod/navigation")
(load "_ido.el")
(load "_scroll.el")
(load "_dired.el")
(load "_projectile.el")
(load "_treemacs.el")

(add-to-list 'load-path "~/.emacs.d/mod/editing")
(load "_path.el")
(load "_magit.el")
(load "_flycheck.el")
(load "_backup.el")
(load "_yesno.el")
(load "_paredit.el")
(load "_autocomplete.el")
(load "_lsp.el")
(load "_eglot.el")
(load "_company.el")
(load "_yasnippet.el")
(load "_indent.el")

(add-to-list 'load-path "~/.emacs.d/mod/visual")
(load "_bar.el")
(load "_line.el")
(load "_space.el")
(load "_font.el")
(load "_rainbow.el")
(load "_showparen.el")

(add-to-list 'load-path "~/.emacs.d/mod/shells")
(load "_eat.el")

(add-to-list 'load-path "~/.emacs.d/mod/languages")
(load "_el.el")
(load "_org.el")
(load "_web.el")
(load "_rest.el")
(load "_yaml.el")
(load "_dockerfile.el")
(load "_sql.el")
(load "_md.el")

(add-to-list 'load-path "~/.emacs.d/mod/themes")
(load "_ef.el")

(add-to-list 'load-path "~/.emacs.d/mod")
(load "_profile.el")
